version: 1-alpha.1

releases:
  lorem-scriptum:
    name: lorem-scriptum
    autodeploy-on: default
    chart: csssr/static-site@~1.1.0
    slack:
      - CKF42GD36 # csssr_builds
    static-params:
      projectID: lorem-scriptum
      tlsSecret: lorem-scriptum-tls
      gzipCompression: enabled
      notFoundPagePath: 404.html
    builds:
      - workflow: deploy-testing.yml
        values:
          buildID: build-{{ .Build.RunID }}
