name: Linters check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Linters check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint js
        run: yarn lint:js

      - name: Run lint style
        run: yarn lint:style
